export const projects = [
  {
    slug: 'warehouse-optimizer',
    num: '01',
    title: 'Warehouse Optimizer — AI Inventory & Fulfillment Platform',
    date: '2026',
    desc: 'AI-powered platform that turns warehouse photos into structured stock data in seconds. A YOLOv8 + EasyOCR + Claude pipeline auto-extracts SKUs from shipment images and updates inventory in real time, paired with order management, ARIMA-based demand forecasting, smart shipment suggestions, a live WebSocket dashboard, and one-click Excel reporting. End-to-end image-to-inventory in under 30 seconds, 25+ documented REST endpoints, and zero-config deployment via `make up`.',
    tags: ['FastAPI', 'PostgreSQL', 'Redis', 'YOLOv8', 'EasyOCR', 'Claude', 'ARIMA', 'React 18', 'WebSockets', 'Docker'],
    highlights: [
      'YOLOv8 + EasyOCR + Claude pipeline auto-extracts SKUs from shipment images',
      'End-to-end image-to-inventory in under 30 seconds',
      '25+ documented REST endpoints with full OpenAPI spec',
      'ARIMA-based demand forecasting with smart shipment suggestions',
      'Live WebSocket dashboard with one-click Excel reporting',
      'Zero-config deployment via `make up` (Docker Compose)',
    ],
    links: { github: 'https://github.com/Jaskirat314276/WAREHOUSE-OPTIMIZATION.git', demo: '' },
  },
  {
    slug: 'smart-school-erp',
    num: '02',
    title: 'Smart School ERP System',
    date: 'Dec 2024',
    desc: 'Full-stack multi-role ERP platform supporting students, parents, faculty, and administrators with RBAC for secure, isolated data access. Containerized with Docker for production-grade deployment.',
    tags: ['React.js', 'Prisma', 'Supabase', 'ClerkAuth', 'Docker'],
    highlights: [
      'Multi-role support: students, parents, faculty, administrators',
      'Role-based access control for isolated, secure data per user type',
      'Authentication and session management via ClerkAuth',
      'Prisma + Supabase for type-safe data access',
      'Containerized with Docker for production-grade deployment',
    ],
    links: { github: 'https://github.com/Jaskirat314276/Winter-Project-24.git', demo: '' },
  },
  {
    slug: 'ai-linkedin-post-generator',
    num: '03',
    title: 'AI LinkedIn Post Generator',
    date: 'Jul 2025',
    desc: 'AI-powered content tool that generates context-aware LinkedIn posts by analyzing influencers\' historical content. Built a RAG pipeline to preserve unique writing styles using LLaMA 3.2.',
    tags: ['LangChain', 'RAG', 'VectorDB', 'Streamlit', 'LLaMA 3.2'],
    highlights: [
      'RAG pipeline preserves each influencer\'s unique writing style',
      'Powered by LLaMA 3.2 with VectorDB-backed retrieval',
      'Context-aware post generation from historical content embeddings',
      'Streamlit interface for fast prompt iteration',
    ],
    links: { github: 'https://github.com/Jaskirat314276/AI-POST-GENRATOR.git', demo: '' },
  },
  {
    slug: 'futureflow-demand-forecast',
    num: '04',
    title: 'FutureFlow — Demand Forecast System',
    date: 'Dec 2024',
    desc: 'Time-series demand forecasting platform using SARIMA modeling. Built Power BI dashboard with KPIs (MoM Growth, YoY Growth, Forecast Error) and DAX measures for real-time monitoring.',
    tags: ['Python', 'SQL', 'statsmodels', 'Power BI', 'DAX'],
    highlights: [
      'SARIMA-based time-series forecasting in Python',
      'Power BI dashboard with MoM Growth, YoY Growth, and Forecast Error KPIs',
      'Custom DAX measures for real-time monitoring',
      'SQL data pipeline feeding the forecasting layer',
    ],
    links: { github: 'https://github.com/Jaskirat314276/DEMAND-ANALYSIS-ARIMA.git', demo: '' },
  },
  {
    slug: 'ev-battery-charger',
    num: '05',
    title: 'Universal EV Battery Charger',
    date: 'Dec 2024',
    desc: 'Designed a forward converter-based battery charger PCB using Eagle CAD. Conducted high-voltage testing up to 300V with full protection circuit for system safety and reliability.',
    tags: ['Eagle CAD', 'SMPS', 'High-Voltage Testing', 'PCB Design'],
    highlights: [
      'Forward converter topology designed in Eagle CAD',
      'High-voltage testing validated up to 300V',
      'Full protection circuit ensuring system safety',
      'Universal compatibility across EV battery chemistries',
    ],
    links: {},
  },
  {
    slug: 'power-factor-correction',
    num: '06',
    title: 'Power Factor Correction Device',
    date: 'May 2025',
    desc: 'Simulated a PFC system using a boost converter topology with ICE3PCS01G IC controller. Achieved improved power factor and reduced THD, validating energy efficiency gains.',
    tags: ['MATLAB', 'Simulink', 'Boost Converter', 'Power Electronics'],
    highlights: [
      'Boost converter topology with ICE3PCS01G IC controller',
      'Simulated end-to-end in MATLAB / Simulink',
      'Improved power factor and reduced Total Harmonic Distortion (THD)',
      'Validated energy efficiency gains via simulation results',
    ],
    links: {},
  },
];

export function getProject(slug) {
  return projects.find((p) => p.slug === slug);
}
